# Generated by Django 2.1.7 on 2019-02-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidget', '0002_auto_20190226_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(blank=True),
        ),
    ]
